# Generated by Django 3.1.7 on 2021-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Name',
            field=models.CharField(max_length=150),
        ),
    ]
