# Generated by Django 3.1.7 on 2021-07-13 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210713_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(max_length=300),
        ),
    ]
